job_gcc_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --with-boost-python=py34 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --with-boost-coroutine=boost_coroutine
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build centrality.rst clustering.rst collection.rst inference.rst correlations.rst draw.rst faq.rst flow.rst generation.rst graph_tool.rst gt_format.rst index.rst modules.rst quickstart.rst spectral.rst stats.rst topology.rst util.rst
  tags:
    - i386

job_gcc_py2_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python2  --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --with-boost-coroutine=boost_coroutine
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build -b doctest . build centrality.rst clustering.rst collection.rst inference.rst correlations.rst draw.rst faq.rst flow.rst generation.rst graph_tool.rst gt_format.rst index.rst modules.rst quickstart.rst spectral.rst stats.rst topology.rst util.rst
  tags:
    - i386

job_gcc_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_clang_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_gcc_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build2 -b doctest . build *.rst
  tags:
    - amd64

job_clang_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build2 -b doctest . build *.rst
  tags:
    - amd64

job_gcc_amd64_nosh:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --disable-sparsehash
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_clang_amd64_nosh:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages  --disable-sparsehash
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64
