job_gcc_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --with-boost-python=py34 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - i386

job_clang_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --with-boost-python=py34 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - i386

job_gcc_py2_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python2  --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - i386

job_clang_py2_386:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python2  --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages s ~/.local/lib/python3.4/site-packages/
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - i386

job_gcc_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_clang_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python3 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_gcc_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64

job_clang_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make
    - make install
    - export PYTHONPATH=$PWD/install/site-packages s ~/.local/lib/python3.4/site-packages/
    - cd doc; OMP_NUM_THREADS=1 python2 /usr/bin/sphinx-build -b doctest . build *.rst
  tags:
    - amd64
